# Generated by Django 5.2.13 on 2026-04-09 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_blog_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='blog_files/'),
        ),
    ]
